notebooks/area_length_filter.ipynb, notebooks/deal_with_errors.ipynb, notebooks/run_with_gcm.ipynb
and checked run_with_gcm and area _length_filter
- I am not sure if I understood it right in deal_with_errors ...
=> additional stuff in deal_with_errors 

notebooks/area_length_filter.ipynb, notebooks/deal_with_errors.ipynb, notebooks/elevation_bands_vs_centerlines.ipynb, notebooks/inversion.ipynb, notebooks/run_with_gcm.ipynb, notebooks/store_and_compress_glacierdirs.ipynb
I am not sure how to remove  the commit from yesterday, but here are also the corrections from the last beginner tutorials
=> now, all beginner tutorials read

notebooks/oggm_shop.ipynb
Hi @fmaussion sorry for the delay on this.. I added the explanation from the other notebook to the itlive section. Also corrected the error on the vector magnitude and changed the glacier to one in Greenland (just for the its-live part though). 
Let me know if this is OK? 
Cheers
=> added more explanation for the itslive data section

notebooks/dem_sources.ipynb, notebooks/preprocessing_errors.ipynb, notebooks/thickness_model.ipynb, notebooks/welcome.ipynb
I read preprocessing_errors  and dem_sources. What is the current default cfg.PARAMS['border'] ? I think it is 20, but 20 does not work as the preprocessing files are 10, 40, 80, 160?  Does it still make sense to use 20 as default setting  or do I misunderstand here something?
=> dem_sources and preprocessing_errors read

notebooks/deal_with_errors.ipynb, notebooks/dem_sources.ipynb, notebooks/elevation_bands_vs_centerlines.ipynb, notebooks/inversion.ipynb, notebooks/inversion_with_frontal_ablation.ipynb, notebooks/kcalving_parameterization.ipynb, notebooks/massbalance_calibration.ipynb, notebooks/merging_glaciers.ipynb, notebooks/preprocessing_errors.ipynb, notebooks/store_and_compress_glacierdirs.ipynb, notebooks/thickness_model.ipynb, notebooks/use_your_own_inventory.ipynb, notebooks/welcome.ipynb
some corrections for 
- inversion_with_frontal_ablation.ipynb
- kcalving_parametrization.ipynb
- thickness_model.ipynb
- use_your_own_inventory.ipynb (here DEM source to SRTM is changed in order that it runs, as described in #10 )
and
- minor further change in dem_sources.ipynb
=> worked through some advanced notebooks 

notebooks/holoviz_intro.ipynb
Finally changed the name! Related to this issue: https://github.com/OGGM/oggm-edu-notebooks/issues/5
=> changed name from PyViz to HoloViz

_toc.yml, notebooks/welcome.ipynb
Changed the name from pyviz to holoviz also for the website. I also built it locally and tested it.
=> Change website for holoviz intro

notebooks/oggm_shop.ipynb
Correct ice velocity unit in the colorbar and legend label. Correct a comment.
=> Mistext correction

notebooks/holoviz_intro.ipynb
This fixes the interesting TypeError of the last plot in the holoviz_intro
=> fixed bug in last plot

notebooks/hydrological_output.ipynb, notebooks/oggm_shop.ipynb
closes https://github.com/OGGM/tutorials/issues/25
=> minor fixes

notebooks/hydrological_output.ipynb
This can only run with https://github.com/OGGM/oggm/pull/1331 - cc @sarah-hanus fyi
=> Document now hydro output options

notebooks/ingest_gridded_data_on_flowlines.ipynb
Hi I started this #34 .. will continue tomorrow evening as I still want to read and write something about the `fixed_dx_elevation_band_flowline` and maybe the rest of the people will like to take over after? ... will commit the rest tomorrow
=> started text for vel tutorial

.github/workflows/build-pages.yml
Caches OGGM downloads to speed up build
=> Add download cache

notebooks/where_are_the_flowlines.ipynb
This PR addresses issue #35 and adds to the where_are_the_flowlines notebook. It adds a part about the new flowline diagnostics.
I would be happy if someone would provide feedback :) (e.g. if it is clear/ if your missing something/ if it's to long)
=> Additions to the where_are_the_flowlines notebook

notebooks/preprocessing_errors.ipynb
- added example error comparison between CRU and ERA5, and between centerlines and elevation band flowlines
- added links to advanced error comparison notebooks
=> added example comparison in preprocessing_error.ipynb + link to advanced ipynb

notebooks/dynamical_spinup.ipynb
Here I added a first draft for the high level description of the dynamical spinup method. For the search for a 'bad' example I will wait until the updated prepro levels are available (related to https://github.com/OGGM/oggm/issues/1388).
This PR is related to https://github.com/OGGM/tutorials/issues/51.
=> added high level description of dynamical spinup method

notebooks/use_your_own_inventory.ipynb
Fixed a bug which caused the tutorial build to crash.
=> fixed bug in use_your_own_inventory

notebooks/deal_with_errors.ipynb, notebooks/inversion.ipynb, notebooks/store_and_compress_glacierdirs.ipynb
Three notebooks had the same issue with referencing to WORKING_DIR without defining this variable before. 
Closes #57
=> Fixing WORKING_DIR variable in three notebooks

notebooks/plot_mass_balance.ipynb, notebooks/welcome.ipynb
This PR adds an example on how to compute the Accumulation Area Ratio to the plot_mass_balance notebook. 
Feel free to make suggestions :) 
@pat-schmitt, thanks for your help on this PR.
=> add AAR computation to plot massbalance notebook

_toc.yml, notebooks/merge_gcm_runs_and_visualize.ipynb, notebooks/welcome.ipynb
Here I add a new workflow notebook I have promised in Issue https://github.com/OGGM/tutorials/issues/31.
This notebook deals more with the postprocessing of different GCM runs (merge all runs into one dataset, calculate regional values out of it, and use HoloViz for interactive visualisation of the results)
=> added Workflow notebook

notebooks/advanced/merge_gcm_runs_and_visualize.ipynb
- removed CMIP5 from `merge_gcm_runs_and_visualize.ipynb` and all mentions of `RCP`
- but "pretended" that one ISIMIP3b GCM is missing for one SSP, just to still be able to show how to handle GCM gaps (and some cells show what happens if you don't handle it right)
- changed colors for some plots to always have the same colors for the same SSPs
=> removed CMIP5 from merge_gcm tutorial, changed colors for some plots

notebooks/10minutes/dynamical_spinup.ipynb, notebooks/10minutes/elevation_bands_vs_centerlines.ipynb, notebooks/10minutes/machine_learning.ipynb, notebooks/10minutes/preprocessed_directories.ipynb, notebooks/10minutes/run_with_gcm.ipynb, notebooks/advanced/centerlines_to_shape.ipynb, notebooks/advanced/dem_sources.ipynb, notebooks/advanced/ingest_gridded_data_on_flowlines.ipynb, notebooks/advanced/merge_gcm_runs_and_visualize.ipynb, notebooks/advanced/preprocessing_errors.ipynb, notebooks/advanced/run_with_a_spinup_and_gcm_data.ipynb, notebooks/advanced/use_your_own_inventory.ipynb, notebooks/advanced/where_are_the_flowlines.ipynb, notebooks/beginner/deal_with_errors.ipynb, notebooks/beginner/full_prepro_workflow.ipynb, notebooks/beginner/inversion.ipynb, notebooks/beginner/oggm_shop.ipynb, notebooks/beginner/plot_mass_balance.ipynb, notebooks/beginner/store_and_compress_glacierdirs.ipynb, notebooks/beginner/working_with_rgi.ipynb, notebooks/construction/dynamical_spinup.ipynb, notebooks/others/dem_comparison.ipynb, notebooks/welcome.ipynb
Ok, that took a bit longer than expected:
I checked all the notebooks (except for `hydrological_output` and `massbalance_calibration`).
- moved that one  https://oggm.org/tutorials/master/notebooks/advanced/dynamical_spinup.html to `construction` as it does not work with OGGMv1.6 at the moment
- updated all the links to other notebooks, due to the new folder structure (at least I tried, I definitely missed some)
- made some plots nicer, added some ylabels 
- subplots were wrong in elevation_bands_vs_centerlines  (changed them to show the right thing, thanks @pat-schmitt ). And made sure that the ylims are the same for subplots ...
=> some improvements, updated links, removed errors

_toc.yml, notebooks/beginner/distribute_flowline.ipynb, notebooks/welcome.ipynb
=> New distribute tutorial

_toc.yml, notebooks/10minutes/dynamical_spinup.ipynb, notebooks/10minutes/elevation_bands_vs_centerlines.ipynb, notebooks/10minutes/machine_learning.ipynb, notebooks/10minutes/preprocessed_directories.ipynb, notebooks/10minutes/run_with_gcm.ipynb, notebooks/advanced/dynamical_spinup.ipynb, notebooks/advanced/massbalance_calibration.ipynb, notebooks/advanced/preprocessing_errors.ipynb, notebooks/construction/dynamical_spinup.ipynb, notebooks/welcome.ipynb, requirements.txt
Here I updated the comprehensive dynamic spinup tutorial to v1.6 and I added content to the 10min dynamic spinup tutorial.
=> Update dynamic spinup

notebooks/tutorials/distribute_flowline.ipynb, notebooks/tutorials/ingest_gridded_data_on_flowlines.ipynb
Here I add examples for `merge_gridded_data` to the tutorial "Ingest gridded products such as ice velocity into OGGM" and for `merge_simulated_thickness` to the tutorial "Display glacier area and thickness changes on a grid".
The additions will only work without an error after PR https://github.com/OGGM/oggm/pull/1691 is merged.
=> add merge_gridded_data to tutorials

notebooks/tutorials/massbalance_calibration.ipynb
Went through this notebook today and noticed a few typos which I've corrected in this PR.
=> minor typo corrections
